---
abstract: 'Yet Another OpenID Consumer/Server support library'
author:
  - 'Lyo Kato, <lyo.kato@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.850'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenID-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::DH::GMP: 0.00005
  Crypt::SSLeay: 0
  Data::Util: 0.50
  HTML::Entities: 0
  HTML::TreeBuilder: 0
  HTML::TreeBuilder::XPath: 0.09
  HTTP::Request: 0
  LWPx::ParanoidAgent: 1.04
  Mouse: 0.17
  MouseX::Types: 0.01
  POSIX::strptime: 0
  String::Random: 0
  URI::Escape: 0
  XML::LibXML: 0
  XRI::Resolution::Lite: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
